"""AM_user pfp default

Revision ID: 0d33f3b35621
Revises: 297d2672c819
Create Date: 2026-05-19 12:12:01.120319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d33f3b35621'
down_revision: Union[str, Sequence[str], None] = '297d2672c819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url_profil_picture', sa.String(), nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url_profil_picture')
    # ### end Alembic commands ###
