"""pfp remove

Revision ID: 1865b18981b3
Revises: 05cf6b55a595
Create Date: 2026-05-18 13:33:15.877714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1865b18981b3'
down_revision: Union[str, Sequence[str], None] = '05cf6b55a595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url_profil_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url_profil_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
