"""AM_remove user pfp

Revision ID: 297d2672c819
Revises: 2c78db4abe16
Create Date: 2026-05-19 12:11:22.287261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297d2672c819'
down_revision: Union[str, Sequence[str], None] = '2c78db4abe16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url_profil_picture')
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('url_profil_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
