"""__add const

Revision ID: 4027a3af756c
Revises: 390f660d454f
Create Date: 2026-05-18 13:01:24.717653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4027a3af756c'
down_revision: Union[str, Sequence[str], None] = '390f660d454f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        constraint_name='birth_date_min',
        table_name='users',
        condition='birth_date < CURRENT_DATE'
    )

    op.create_check_constraint(
        constraint_name='end_date_min',
        table_name='schedules',
        condition='end_date = NULL OR end_date > start_date'
    )
    
    op.create_check_constraint(
        constraint_name='days_of_week_range',
        table_name='exercice_to_dos',
        condition='days_of_week BETWEEN 0 AND 6'
    )
    op.create_check_constraint(
        constraint_name='repetition_min',
        table_name='exercice_to_dos',
        condition='repetition > 0'
    )
    op.create_check_constraint(
        constraint_name='series_min',
        table_name='exercice_to_dos',
        condition='series > 0'
    )

    op.create_check_constraint(
        constraint_name='name_format',
        table_name='exercices',
        condition='name ~ \'[a-zA-Z_- ]{4,}\''
    )
    op.create_check_constraint(
        constraint_name='url_details_format',
        table_name='exercices',
        condition='url_details ~ \'^https://.*(.html)\''
    )
    op.create_check_constraint(
        constraint_name='url_image_format',
        table_name='exercices',
        condition='url_image ~ \'^https://.*(.png|.jpg|.jpeg|.webp)\''
    )
    op.create_check_constraint(
        constraint_name='amplitude_range',
        table_name='exercices',
        condition='amplitude BETWEEN 0.0 AND 1.0'
    )

    op.create_check_constraint(
        constraint_name='date_check',
        table_name='exercices',
        condition='amplitude BETWEEN 0.0 AND 1.0'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
