"""edit exercice constraint

Revision ID: 73e85d13c19d
Revises: f6dcf0d4a38c
Create Date: 2026-05-19 16:40:37.011006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e85d13c19d'
down_revision: Union[str, Sequence[str], None] = 'f6dcf0d4a38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name='date_check',
        table_name='exercices'
    )

    op.drop_constraint(
        constraint_name='url_details_format',
        table_name='exercices'
    )
    op.create_check_constraint(
        constraint_name='url_details_format',
        table_name='exercices',
        condition='url_details = NULL OR url_details ~ \'^https://.*(.html)\''
    )
    
    op.drop_constraint(
        constraint_name='url_image_format',
        table_name='exercices'
    )
    op.create_check_constraint(
        constraint_name='url_image_format',
        table_name='exercices',
        condition='url_image = NULL OR url_image ~ \'^https://.*(.png|.jpg|.jpeg|.webp)\''
    )

    op.alter_column('exercices', 'url_details',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercices', 'url_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercices', 'url_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercices', 'url_details',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
