"""edit constraint on days of week

Revision ID: 80a183130b56
Revises: 9fb482313ecf
Create Date: 2026-05-22 16:50:07.771887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a183130b56'
down_revision: Union[str, Sequence[str], None] = '9fb482313ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name='days_of_week_range',
        table_name='exercice_to_dos'
    )
    op.create_check_constraint(
        constraint_name='days_of_week_range',
        table_name='exercice_to_dos',
        condition='days_of_week BETWEEN 1 AND 127'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
