"""edit regex name exercice

Revision ID: 9fb482313ecf
Revises: 73e85d13c19d
Create Date: 2026-05-19 16:49:53.515228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb482313ecf'
down_revision: Union[str, Sequence[str], None] = '73e85d13c19d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint(
        constraint_name='name_format',
        table_name='exercices'
    )
    op.create_check_constraint(
        constraint_name='name_format',
        table_name='exercices',
        condition='name ~ \'[a-zA-Z_ -]{4,}\''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
