"""add user pfp

Revision ID: a3422a6aa562
Revises: c039bde33b44
Create Date: 2026-05-18 09:19:24.316586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3422a6aa562'
down_revision: Union[str, Sequence[str], None] = 'c039bde33b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url_profil_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url_profil_picture')
    # ### end Alembic commands ###
