"""Init migration (with role)

Revision ID: afe208e8378b
Revises: 
Create Date: 2026-05-17 15:04:42.137252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe208e8378b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url_details', sa.String(), nullable=False),
    sa.Column('url_image', sa.String(), nullable=False),
    sa.Column('amplitude', sa.Float(), nullable=False),
    sa.Column('is_minutes', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercice_to_dos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('exercice_id', sa.Integer(), nullable=False),
    sa.Column('days_of_week', sa.Integer(), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('additional_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exercice_id'], ['exercices.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    #days_of_week_range=CheckConstraint(<sqlalchemy.sql.elements.TextClause object at 0x00000243BC870EF0>),
    #repetition_min=CheckConstraint(<sqlalchemy.sql.elements.TextClause object at 0x00000243BC855B50>),
    #series_min=CheckConstraint(<sqlalchemy.sql.elements.TextClause object at 0x00000243BC843150>)
    )
    op.create_table('check_exercices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercice_to_do_id', sa.Integer(), nullable=False),
    sa.Column('date_check', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercice_to_do_id'], ['exercice_to_dos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_exercices')
    op.drop_table('exercice_to_dos')
    op.drop_table('schedules')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('exercices')
    # ### end Alembic commands ###
