"""pfp remove +

Revision ID: b9d07f83d964
Revises: 1865b18981b3
Create Date: 2026-05-18 13:33:50.936062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d07f83d964'
down_revision: Union[str, Sequence[str], None] = '1865b18981b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url_profil_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url_profil_picture')
    # ### end Alembic commands ###
