"""edit regex

Revision ID: ba139d95f83f
Revises: 0d33f3b35621
Create Date: 2026-05-19 16:30:03.932741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba139d95f83f'
down_revision: Union[str, Sequence[str], None] = '0d33f3b35621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name='phone_number_format',
        table_name='users'
    )
    op.create_check_constraint(
        constraint_name='phone_number_format',
        table_name='users',
        condition='phone_number ~ \'^[0-9 +-]*$\''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
