"""add user pfp

Revision ID: e1a026927552
Revises: a3422a6aa562
Create Date: 2026-05-18 09:20:41.842621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a026927552'
down_revision: Union[str, Sequence[str], None] = 'a3422a6aa562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'checks')

    op.create_check_constraint(
        constraint_name='email_format',
        table_name='users',
        condition='email ~ \'^.*@.*..*$\''
    )
    op.create_check_constraint(
        constraint_name='phone_number_format',
        table_name='users',
        condition='phone_number ~ \'^[0-9- ]*$\''
    )
    op.create_check_constraint(
        constraint_name='height_min',
        table_name='users',
        condition='height > 0'
    )
    op.create_check_constraint(
        constraint_name='weight_min',
        table_name='users',
        condition='weight > 0'
    )
    #op.create_check_constraint(
    #    constraint_name='birth_date_min',
    #    table_name='users',
    #    condition='birth_date < CURRENT_DATE'
    #)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('checks', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
