"""edit constr

Revision ID: f00a3aa5ca3d
Revises: 7cdbc60e8f7c
Create Date: 2026-05-18 12:59:42.937710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00a3aa5ca3d'
down_revision: Union[str, Sequence[str], None] = '7cdbc60e8f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        constraint_name='phone_number_format',
        table_name='users',
        condition='phone_number ~ \'^[0-9- ]*$\''
    )
    op.create_check_constraint(
        constraint_name='height_min',
        table_name='users',
        condition='height > 0'
    )
    op.create_check_constraint(
        constraint_name='weight_min',
        table_name='users',
        condition='weight > 0'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
